### ISSUE TITLE
Spring Boot Tools Plugin Causes Java Searching to Hang in Large Projects (3300 Java Files)

### ISSUE THREAD

**Issue by Skyxim** [spring-projects/sts4#1419]
**Describe the bug**

When loading a Spring Boot project containing approximately 3300 Java files, the Spring Boot Tools plugin (v1.58.0) causes the Java Searching phase of the Java Extension Pack to be stuck for a prolonged period, and the project fails to load. However, disabling the Spring Boot Tools plugin ensures that the Java Searching phase completes successfully.
Additionally, the issue persists even when using the pre-release version of Spring Boot Tools.
While the project is stuck, an exception is observed in the Spring Boot Tools logs, which seems to be related to the issue.

**To Reproduce**
1.	Install:
	•	Spring Boot Tools (v1.58.0 or pre-release).
	•	Java Extension Pack (including Language Support for Java(TM) by Red Hat v1.37.0).
2.	Use Remote SSH to open a Spring Boot project with 3300 Java files.
3.	Observe that Java Searching gets stuck.
4.	Check the Spring Boot Tools logs for an exception.
5.	Disable Spring Boot Tools and reload the project; it loads successfully.
<img width="239" alt="image" src="https://github.com/user-attachments/assets/bcd9a53c-0a5c-4463-a6fe-08764ebaca8e">

log

```sh
19:32:43.343 [pool-3-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - workspace symbol computation done: 0
19:32:43.343 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - request for workspace symbols arrived: @/
19:32:43.343 [pool-3-thread-2] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - workspace symbol computation done: 0
19:32:43.343 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - request for workspace symbols arrived: @/
19:32:43.343 [pool-3-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - workspace symbol computation done: 0
19:32:43.343 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - request for workspace symbols arrived: @/
19:32:43.343 [pool-3-thread-2] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - workspace symbol computation done: 0
19:32:43.343 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - request for workspace symbols arrived: @/
19:32:43.343 [pool-3-thread-2] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - workspace symbol computation done: 0
19:32:43.343 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - request for workspace symbols arrived: @/
19:32:43.343 [pool-3-thread-2] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - workspace symbol computation done: 0
19:32:43.343 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - request for workspace symbols arrived: @/
19:32:43.343 [pool-3-thread-2] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - workspace symbol computation done: 0
19:32:43.343 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - request for workspace symbols arrived: @/
19:32:43.343 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - request for workspace symbols arrived: @/
19:32:43.343 [pool-3-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - workspace symbol computation done: 0
19:32:43.343 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - request for workspace symbols arrived: @/
19:32:43.343 [pool-3-thread-6] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - workspace symbol computation done: 0
19:32:43.343 [pool-3-thread-2] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - workspace symbol computation done: 0
19:32:43.343 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - request for workspace symbols arrived: @/
19:32:43.343 [pool-3-thread-2] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - workspace symbol computation done: 0
19:32:43.343 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - request for workspace symbols arrived: @/
19:32:43.343 [pool-3-thread-2] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - workspace symbol computation done: 0
19:32:43.343 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - request for workspace symbols arrived: @/
19:32:43.343 [pool-3-thread-6] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - workspace symbol computation done: 0
19:32:43.512 [Simple-Language-Server main thread] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - file created event: [file:///home/frost/codes/work/test/.attach_pid237143]
19:32:43.513 [Simple-Language-Server main thread] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - file deleted event: [file:///home/frost/codes/work/test/.attach_pid237143]
19:32:50.331 [parallel-5] ERROR o.s.i.v.b.jdt.ls.JdtLsProjectCache - Unexpected error registering classpath listener with JDT.
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'Mono.thenReturn ⇢ at org.springframework.ide.vscode.commons.languageserver.java.ls.ClasspathListenerManager.addClasspathListener(ClasspathListenerManager.java:144)' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:296)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoTimeout] :
	reactor.core.publisher.Mono.timeout(Mono.java:5008)
	org.springframework.ide.vscode.boot.jdt.ls.JdtLsProjectCache.enableClasspathListener(JdtLsProjectCache.java:274)
Error has been observed at the following site(s):
	*________Mono.timeout ⇢ at org.springframework.ide.vscode.boot.jdt.ls.JdtLsProjectCache.enableClasspathListener(JdtLsProjectCache.java:274)
	|_ Mono.doOnSubscribe ⇢ at org.springframework.ide.vscode.boot.jdt.ls.JdtLsProjectCache.enableClasspathListener(JdtLsProjectCache.java:275)
	|_   Mono.doOnSuccess ⇢ at org.springframework.ide.vscode.boot.jdt.ls.JdtLsProjectCache.enableClasspathListener(JdtLsProjectCache.java:276)
Original Stack Trace:
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:296)
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:281)
		at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:420)
		at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162)
		at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:270)
		at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:285)
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
		at java.base/java.lang.Thread.run(Thread.java:1583)
19:32:50.333 [parallel-5] INFO  o.s.i.v.b.jdt.ls.JdtLsProjectCache - Enable classpath listener enabled = false current enablement = true
19:32:50.333 [parallel-5] INFO  o.s.i.v.b.jdt.ls.JdtLsProjectCache - Removing classpath listener enabled=false
19:32:50.333 [parallel-5] INFO  o.s.i.v.b.jdt.ls.JdtLsProjectCache - Project Observer is not supported
19:32:50.333 [parallel-5] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'Mono.thenReturn ⇢ at org.springframework.ide.vscode.commons.languageserver.java.ls.ClasspathListenerManager.addClasspathListener(ClasspathListenerManager.java:144)' (and no fallback has been configured)
Caused by: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'Mono.thenReturn ⇢ at org.springframework.ide.vscode.commons.languageserver.java.ls.ClasspathListenerManager.addClasspathListener(ClasspathListenerManager.java:144)' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:296)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoTimeout] :
	reactor.core.publisher.Mono.timeout(Mono.java:5008)
	org.springframework.ide.vscode.boot.jdt.ls.JdtLsProjectCache.enableClasspathListener(JdtLsProjectCache.java:274)
Error has been observed at the following site(s):
	*________Mono.timeout ⇢ at org.springframework.ide.vscode.boot.jdt.ls.JdtLsProjectCache.enableClasspathListener(JdtLsProjectCache.java:274)
	|_ Mono.doOnSubscribe ⇢ at org.springframework.ide.vscode.boot.jdt.ls.JdtLsProjectCache.enableClasspathListener(JdtLsProjectCache.java:275)
	|_   Mono.doOnSuccess ⇢ at org.springframework.ide.vscode.boot.jdt.ls.JdtLsProjectCache.enableClasspathListener(JdtLsProjectCache.java:276)
	|_     Mono.doOnError ⇢ at org.springframework.ide.vscode.boot.jdt.ls.JdtLsProjectCache.enableClasspathListener(JdtLsProjectCache.java:277)
Original Stack Trace:
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:296)
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:281)
		at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:420)
		at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162)
		at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:270)
		at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:285)
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
		at java.base/java.lang.Thread.run(Thread.java:1583)
19:35:38.865 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleTextDocumentService - Closed: file:///home/frost/codes/work/test/yudao-module-infra/yudao-module-infra-biz/src/test/resources/logback.xml
19:35:38.865 [pool-13-thread-1] INFO  o.s.i.v.b.j.u.CompilationUnitCache - Invalidate AST for file:///home/frost/codes/work/test/yudao-module-infra/yudao-module-infra-biz/src/test/resources/logback.xml
19:35:39.492 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleTextDocumentService - Closed: file:///home/frost/codes/work/test/yudao-module-system/yudao-module-system-biz/src/test/resources/logback.xml
19:35:39.492 [pool-13-thread-1] INFO  o.s.i.v.b.j.u.CompilationUnitCache - Invalidate AST for file:///home/frost/codes/work/test/yudao-module-system/yudao-module-system-biz/src/test/resources/logback.xml
19:35:41.966 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleTextDocumentService - Closed: file:///home/frost/codes/work/test/yudao-server/src/main/resources/logback-spring.xml
19:35:41.966 [pool-13-thread-1] INFO  o.s.i.v.b.j.u.CompilationUnitCache - Invalidate AST for file:///home/frost/codes/work/test/yudao-server/src/main/resources/logback-spring.xml
19:36:54.083 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleLanguageServer - shutdown: request arrived
19:36:54.084 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleLanguageServer - shutdown: call shutdown handler
19:36:54.087 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleLanguageServer - shutdown: complete
19:36:54.094 [pool-13-thread-1] INFO  o.s.i.v.c.l.u.SimpleLanguageServer - exit: notification received
19:54:44.687 [Simple-Language-Server main thread] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - file created event: [file:///home/frost/codes/work/test/.git/index]
```
**Sample**

**Comment by martinlippert** [comment]
Can you take a look into the log of the Java tooling as well and attach the output here? (both the java extension log and the java language server log

You can open both via the command for `Java: Open All Log Files`

The exception above looks like the Spring tooling waits too long for the Java tooling to respond when registering some listeners, so might be worth looking into what happens over there as well.

If you import the project without the Spring Tools enabled, how long does it take for the project to be fully imported and the Java tooling is done with background jobs?

**Comment by BoykoAlex** [comment]
@Skyxim thanks for the sample project!!! I wasn't able to reproduce the issue so far. By "Once in 3 times" you mean you execute "Reload Window" command in VSCode and every third time you see "Searching..." op from Java tooling gets stuck at startup, correct?
I noticed some odd log statements on the Java Tooling log. Closer to the end Java LS received a "shutdown" message and started stopping plugins. At the same time Spring LS attempts to register classpath listeners and fails because Java LS already stopped many bundles hence classpath listener fails to be registered:
```
!ENTRY org.eclipse.jdt.ls.core 1 0 2024-11-29 12:51:32.980
!MESSAGE Shutdown received... waking up main thread

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-11-29 12:51:32.984
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is stopping:

!ENTRY org.springframework.tooling.jdt.ls.extension 1 0 2024-11-29 12:51:33.001
!MESSAGE ClasspathListenerHandler executeCommand sts.java.addClasspathListener, [sts4.classpath.HoZLCFTH]
```

I'd try and look for the reason for the shutdown on the Java LS side... All of this requires investigation...

**Comment by martinlippert** [comment]
Thanks a lot @Skyxim for the update on this and glad to hear that it looks like the problem is solved for the moment. Since there is nothing we can further investigate here, let's close the issue. If you come across this issue again, please comment and we can re-open anytime.

**Comment by CloudSen** [comment]
Unfortunately, this problem still exists.  

# Environment
- OS: MACOS 15.2 (24C101) M1
- IDE Version: VSCODE 1.96.4
- Plugin Version:  
  - redhat.java: 1.39.0 (January 22nd, 2025)
  - vmware.vscode-spring-boot: 1.59.0
- User Config:
```
{
    "window.commandCenter": 1,
    "editor.fontSize": 12,
    "editor.tabSize": 2,
    "terminal.integrated.fontSize": 12,
    "editor.minimap.sectionHeaderFontSize": 6,
    "window.zoomLevel": 0,
    "editor.codeLensFontFamily": "JetBrains Mono, Hack, Menlo, Monaco, 'Courier New', monospace",
    "editor.inlineSuggest.fontFamily": "JetBrains Mono, Hack, Menlo, Monaco, 'Courier New', monospace",
    "terminal.integrated.fontFamily": "MesloLGS NF",
    "workbench.iconTheme": "material-icon-theme",
    "editor.fontFamily": "JetBrains Mono, Hack, Menlo, Monaco, 'Courier New', monospace",
    "workbench.colorTheme": "Default Light+",
    "editor.foldingImportsByDefault": true,
    "workbench.startupEditor": "none",
    "extensions.ignoreRecommendations": true,
    "workbench.panel.showLabels": false,
    "explorer.confirmDelete": false,

    "projectManager.git.baseFolders": [
        "/Users/clouds3n/Coding/cisdi/java/datakits"
    ],
    "projectManager.tags": [
        "Personal",
        "OpenSource",
        "Cisdi",
        "Datakits"
    ],


    "gitblame.inlineMessageEnabled": true,
    "git.autofetch": true,
    "git.replaceTagsWhenPull": true,
    "git.confirmSync": false,
    "git.pruneOnFetch": true,
    "git.allowForcePush": true,
    "java.jdt.ls.java.home": "/Users/clouds3n/.sdkman/candidates/java/21.0.2-zulu",
    "java.autobuild.enabled": false,
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-1.8",
            "path": "/Users/clouds3n/.sdkman/candidates/java/8.0.402-zulu",
            "default": true
        },
        {
            "name": "JavaSE-17",
            "path": "/Users/clouds3n/.sdkman/candidates/java/17.0.12.fx-zulu"
        },
        {
            "name": "JavaSE-21",
            "path": "/Users/clouds3n/.sdkman/candidates/java/21.0.2-zulu"
        }
    ],
    "redhat.telemetry.enabled": false,

    "java.sources.organizeImports.starThreshold": 5,
    "java.sources.organizeImports.staticStarThreshold": 3,
    "java.completion.importOrder": [
        "",
        "javax",
        "java",
        "#"
    ],
    "java.saveActions.organizeImports": true,
    "java.dependency.packagePresentation": "hierarchical",
    "java.compile.nullAnalysis.mode": "automatic",
    "java.configuration.updateBuildConfiguration": "automatic",
    "java.jdt.ls.androidSupport.enabled": "off",
    "java.maven.updateSnapshots": true,
    "java.editor.reloadChangedSources": "auto",
    "java.completion.favoriteStaticMembers": [  
        "org.junit.Assert.*",
        "org.junit.Assume.*",
        "org.junit.jupiter.api.Assertions.*",
        "org.junit.jupiter.api.Assumptions.*",
        "org.junit.jupiter.api.DynamicContainer.*",
        "org.junit.jupiter.api.DynamicTest.*",
        "org.mockito.Mockito.*",
        "org.mockito.ArgumentMatchers.*",
        "org.mockito.Answers.*",
        "org.assertj.core.api.Assertions.assertThat",
        "cn.cisdigital.datakits.gateway.open.spi.abs.AdaptorParamUtils"
    ],


    "maven.view": "hierarchical",
    "maven.pomfile.autoUpdateEffectivePOM": true,
    "maven.executable.options": "-T 8C",

   
    "native-ascii-converter.letter-case": "Upper case",
    "native-ascii-converter.auto-conversion-on-save": true,
    "native-ascii-converter.auto-conversion-on-activate": true,
    "native-ascii-converter.use-files.associations": true,
    "files.associations": {
        "*.properties": "properties",
        "*_en_US.properties": "properties",
        "*_ru_RU.properties": "properties",
        "*_zh_CN.properties": "properties",
    },

    "gitlab-mr.accessTokens": {
        "https://git.cisdigital.cn": "md83S3V9DkPX9sWS88xv"
    },
}
```
# What Happend
When I open the project, the build always gets stuck at:

```
90014eca Repository registry initialization [Done]
c9f159a9 Importing Maven project(s) [Done]
e4d5e13e Send Classpath Notifications [Done]
b18b1e41 Refreshing workspace [Done]
3296788a Validate documents [Done]
5a6a8360 Publish Diagnostics [Done]
eefe1760 Searching... - 0% 
```

I tried running Java: Clean Java Language Server Workspace and mvn clean, and even reinstalled the plugin, but none of it worked.  
If I disable `vmware.vscode-spring-boot` plugin, all problems are solved.

# logs when disable `vmware.vscode-spring-boot` plugin

```
{
  message: "Use the JDK from 'java.jdt.ls.java.home' setting as the initial default project JDK.",
  level: 'info',
  timestamp: '2025-01-23 15:41:49.379'
}
{
  message: 'Starting Java server with: /Users/clouds3n/.sdkman/candidates/java/21.0.2-zulu/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Djava.import.generatesMetadataFilesAtProjectRoot=false -DDetectVMInstallationsJob.disabled=true -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -Xlog:disable -javaagent:/Users/clouds3n/.vscode/extensions/redhat.java-1.39.0-darwin-arm64/lombok/lombok-1.18.34.jar -jar /Users/clouds3n/.vscode/extensions/redhat.java-1.39.0-darwin-arm64/server/plugins/org.eclipse.equinox.launcher_1.6.900.v20240613-2009.jar -configuration /Users/clouds3n/Library/Application Support/Code/User/globalStorage/redhat.java/1.39.0/config_ss_mac -data /Users/clouds3n/Library/Application Support/Code/User/workspaceStorage/008f8c1c57f7be98fd048721dc4a9186/redhat.java/ss_ws',
  level: 'info',
  timestamp: '2025-01-23 15:41:49.419'
}
{
  message: 'WARNING: Using incubator modules: jdk.incubator.vector\n',
  level: 'info',
  timestamp: '2025-01-23 15:41:49.668'
}
{
  message: 'Starting Java server with: /Users/clouds3n/.sdkman/candidates/java/21.0.2-zulu/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Djava.import.generatesMetadataFilesAtProjectRoot=false -DDetectVMInstallationsJob.disabled=true -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -Xlog:disable -javaagent:/Users/clouds3n/.vscode/extensions/redhat.java-1.39.0-darwin-arm64/lombok/lombok-1.18.34.jar -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/clouds3n/Library/Application Support/Code/User/workspaceStorage/008f8c1c57f7be98fd048721dc4a9186/redhat.java -Daether.dependencyCollector.impl=bf -jar /Users/clouds3n/.vscode/extensions/redhat.java-1.39.0-darwin-arm64/server/plugins/org.eclipse.equinox.launcher_1.6.900.v20240613-2009.jar -configuration /Users/clouds3n/Library/Application Support/Code/User/globalStorage/redhat.java/1.39.0/config_mac -data /Users/clouds3n/Library/Application Support/Code/User/workspaceStorage/008f8c1c57f7be98fd048721dc4a9186/redhat.java/jdt_ws',
  level: 'info',
  timestamp: '2025-01-23 15:41:49.719'
}
{
  message: 'WARNING: Using incubator modules: jdk.incubator.vector\n',
  level: 'info',
  timestamp: '2025-01-23 15:41:49.791'
}
{
  message: '1月 23, 2025 3:41:50 下午 org.apache.aries.spifly.BaseActivator log\n' +
    '信息: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic\n',
  level: 'info',
  timestamp: '2025-01-23 15:41:50.216'
}
{
  message: '1月 23, 2025 3:41:50 下午 org.apache.aries.spifly.BaseActivator log\n' +
    '信息: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic\n',
  level: 'info',
  timestamp: '2025-01-23 15:41:50.217'
}
{
  message: '[Error - 15:41:50] 2025年1月23日 15:41:50 An internal error occurred during: "Initialize After Load".\n' +
    'Cannot invoke "org.osgi.framework.Bundle.start(int)" because the return value of "org.eclipse.core.runtime.Platform.getBundle(String)" is null\n' +
    'java.lang.NullPointerException: Cannot invoke "org.osgi.framework.Bundle.start(int)" because the return value of "org.eclipse.core.runtime.Platform.getBundle(String)" is null\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.startBundle(BundleUtils.java:360)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin$1.run(JavaLanguageServerPlugin.java:196)\n' +
    '\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)\n',
  level: 'info',
  timestamp: '2025-01-23 15:41:50.624'
}
{
  message: "[Error - 15:41:55] 2025年1月23日 15:41:55 org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request workspace/executeClientCommand failed with message: command 'vscode-spring-boot.ls.start' not found\n" +
    "org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request workspace/executeClientCommand failed with message: command 'vscode-spring-boot.ls.start' not found\n" +
    "java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request workspace/executeClientCommand failed with message: command 'vscode-spring-boot.ls.start' not found\n" +
    '\tat java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.JavaClientConnection.executeClientCommand(JavaClientConnection.java:89)\n' +
    '\tat org.springframework.tooling.jdt.ls.extension.JdtLsExtensionPlugin.lambda$2(JdtLsExtensionPlugin.java:47)\n' +
    '\tat org.springframework.tooling.jdt.ls.commons.BootProjectTracker.fireEvent(BootProjectTracker.java:74)\n' +
    '\tat org.springframework.tooling.jdt.ls.commons.BootProjectTracker.processProject(BootProjectTracker.java:61)\n' +
    '\tat org.springframework.tooling.jdt.ls.commons.BootProjectTracker.<init>(BootProjectTracker.java:51)\n' +
    '\tat org.springframework.tooling.jdt.ls.extension.JdtLsExtensionPlugin.lambda$1(JdtLsExtensionPlugin.java:57)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)\n' +
    '\tat org.springframework.tooling.jdt.ls.extension.JdtLsExtensionPlugin$1.done(JdtLsExtensionPlugin.java:84)\n' +
    '\tat org.eclipse.core.internal.jobs.JobListeners.sendEvent(JobListeners.java:153)\n' +
    '\tat org.eclipse.core.internal.jobs.JobListeners.sendEventsAsync(JobListeners.java:140)\n' +
    '\tat org.eclipse.core.internal.jobs.JobListeners.waitAndSendEvents(JobListeners.java:80)\n' +
    '\tat org.eclipse.core.internal.jobs.JobManager.withWriteLock(JobManager.java:551)\n' +
    '\tat org.eclipse.core.internal.jobs.JobManager.endJob(JobManager.java:756)\n' +
    '\tat org.eclipse.core.internal.jobs.WorkerPool.endJob(WorkerPool.java:117)\n' +
    '\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:83)\n' +
    "Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request workspace/executeClientCommand failed with message: command 'vscode-spring-boot.ls.start' not found\n" +
    '\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:220)\n' +
    '\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:204)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)\n' +
    '\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)\n' +
    '\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)\n' +
    '\tat org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)\n' +
    '\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)\n' +
    '\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n' +
    '\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n' +
    '\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n' +
    '\tat java.base/java.lang.Thread.run(Thread.java:1583)\n',
  level: 'info',
  timestamp: '2025-01-23 15:41:55.532'
}
{
  message: '[Error - 15:45:28] 2025年1月23日 15:45:28 Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".\n' +
    'cisdi-datakits-build-parent does not exist\n' +
    'Java Model Exception: Error in Java Model (code 969): cisdi-datakits-build-parent does not exist\n' +
    '\tat org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:546)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2549)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:2339)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2412)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaProject.getAllPackageFragmentRoots(JavaProject.java:1784)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaProject.getAllPackageFragmentRoots(JavaProject.java:1775)\n' +
    '\tat com.microsoft.jdtls.ext.core.ProjectCommand.getMainClasses(ProjectCommand.java:243)\n' +
    '\tat com.microsoft.jdtls.ext.core.CommandHandler.executeCommand(CommandHandler.java:35)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)\n' +
    '\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:610)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)\n',
  level: 'info',
  timestamp: '2025-01-23 15:45:28.998'
}
{
  message: '[Error - 15:45:28] 2025年1月23日 15:45:28 Error in calling delegate command handler\n' +
    'cisdi-datakits-build-parent does not exist\n' +
    'Java Model Exception: Error in Java Model (code 969): cisdi-datakits-build-parent does not exist\n' +
    '\tat org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:546)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2549)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:2339)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2412)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaProject.getAllPackageFragmentRoots(JavaProject.java:1784)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaProject.getAllPackageFragmentRoots(JavaProject.java:1775)\n' +
    '\tat com.microsoft.jdtls.ext.core.ProjectCommand.getMainClasses(ProjectCommand.java:243)\n' +
    '\tat com.microsoft.jdtls.ext.core.CommandHandler.executeCommand(CommandHandler.java:35)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)\n' +
    '\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:610)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)\n',
  level: 'info',
  timestamp: '2025-01-23 15:45:28.999'
}

```


# logs enable`vmware.vscode-spring-boot` plugin

redhat.java plugin syntax server log:
```
WARNING: Using incubator modules: jdk.incubator.vector
[Error - 14:34:44] 2025年1月23日 14:34:44 An internal error occurred during: "Initialize After Load".
Cannot invoke "org.osgi.framework.Bundle.start(int)" because the return value of "org.eclipse.core.runtime.Platform.getBundle(String)" is null
java.lang.NullPointerException: Cannot invoke "org.osgi.framework.Bundle.start(int)" because the return value of "org.eclipse.core.runtime.Platform.getBundle(String)" is null
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.startBundle(BundleUtils.java:360)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin$1.run(JavaLanguageServerPlugin.java:196)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by martinlippert** [comment]
@CloudSen Thanks for updating this issue with all the details, much appreciated. I have a few questions:

- It sounds like this is 100% reproducible in your case, is that correct?
- Does switching to the pre-release of the spring-boot tools extension change anything?
- Do you have a project that you can share that can help to reproduce this problem?
- Do you use Gradle in your projects? I recently observed issues when having Gradle projects in the workspace, so I am wondering whether that is the case for you as well

**Comment by CloudSen** [comment]
> [@CloudSen](https://github.com/CloudSen) Thanks for updating this issue with all the details, much appreciated. I have a few questions:
> 
> * It sounds like this is 100% reproducible in your case, is that correct?
> * Does switching to the pre-release of the spring-boot tools extension change anything?
> * Do you have a project that you can share that can help to reproduce this problem?
> * Do you use Gradle in your projects? I recently observed issues when having Gradle projects in the workspace, so I am wondering whether that is the case for you as well

Thank you for your reply! Below are my answers to your questions:

1. Yes, this issue is 100% reproducible in a specific project, but it works fine in other projects

2. I have tried switching to the pre-release version, but the issue persists. However, the progress is no longer stuck at 0% but at 78%.
- redhat.java plugin => pre-release & vmware.vscode-spring-boot => release: The issue still exists.

- redhat.java plugin => release & vmware.vscode-spring-boot => pre-release: The issue still exists.

- redhat.java plugin => pre-release & vmware.vscode-spring-boot => pre-release: The issue still exists.

With my project, it should get stuck at:
```
c1d4bdec LookupJDKToolchainsJob [Done]  
1f266fc0 Resolve plugin dependency [Done]  
72c92888 Send Classpath Notifications [Done]  
837d46f6 Send Classpath Notifications [Done]  
fd9a4f15 Refreshing workspace [Done]  
48870b37 Searching... - 78% 519 files to index (/cisdi-datakits-cache-abs)  
```

3. I have uploaded a project that can reproduce the issue: https://github.com/CloudSen/vscode_java_build_hang_demo.
And this is my vscode profile: https://gist.github.com/CloudSen/f2605bfc5e6cbc381f1393915e9d921e

4. Sorry, I currently do not have any Gradle projects. All my projects are Maven-based

Hope the above info helps!

**Comment by martinlippert** [comment]
Thanks @CloudSen for the additional details. Unfortunately I am having difficulties building your sample project even outside of VSCode, running `mvn clean package` from the root directly results in various build errors. Do you have a few steps at hand how to setup and build the project from scratch?

**Comment by CloudSen** [comment]
> Thanks [@CloudSen](https://github.com/CloudSen) for the additional details. Unfortunately I am having difficulties building your sample project even outside of VSCode, running `mvn clean package` from the root directly results in various build errors. Do you have a few steps at hand how to setup and build the project from scratch?

Sry,  I forgot to check the project's usability earlier. Now I've cleaned up the useless code and Maven dependencies.
What's more important is that this time, I'm on Windows 11, using the same VSCode profile to modify the demo project, and it still gets stuck during the "Searching" process.

Here are the steps to build the project:
1. use jdk8
2. Go to the `cisdi-datakits-dependencies` directory, then run `mvn clean install`
3. Go back to the root directory
4. Run `mvn clean package -Dmaven.test.skip`

**Comment by martinlippert** [comment]
Thanks @CloudSen for the additional details and the cleanup work, much appreciated. I can successfully build and import the project now, and I can reproduce the issue. The Java indexing is stuck around 78%... 👍 

For the technical analysis:
The underlying thread dump of the Java language server show something like this

```
"Java indexing" #36 [59907] daemon prio=5 os_prio=31 cpu=8958.72ms elapsed=107.93s tid=0x0000000110250200 nid=59907 waiting on condition  [0x000000017351d000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@21.0.5/Native Method)
	- parking to wait for  <0x00000007eb08d498> (a java.util.concurrent.ForkJoinTask$AdaptedCallable)
	at java.util.concurrent.locks.LockSupport.park(java.base@21.0.5/Unknown Source)
	at java.util.concurrent.ForkJoinTask.awaitDone(java.base@21.0.5/Unknown Source)
	at java.util.concurrent.ForkJoinTask.get(java.base@21.0.5/Unknown Source)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.performParallelSearch(PatternSearchJob.java:154)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.execute(PatternSearchJob.java:115)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.performConcurrentJob(JobManager.java:286)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.searchAllSecondaryTypeNames(BasicSearchEngine.java:1727)
	at org.eclipse.jdt.internal.core.JavaModelManager.secondaryTypesSearching(JavaModelManager.java:5067)
	at org.eclipse.jdt.internal.core.JavaModelManager.secondaryTypes(JavaModelManager.java:4922)
	at org.eclipse.jdt.internal.core.search.matching.ClasspathSourceDirectory.directoryTable(ClasspathSourceDirectory.java:79)
	at org.eclipse.jdt.internal.core.search.matching.ClasspathSourceDirectory.findClass(ClasspathSourceDirectory.java:117)
	at org.eclipse.jdt.internal.core.search.matching.ClasspathSourceDirectory.findClass(ClasspathSourceDirectory.java:113)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.findClass(JavaSearchNameEnvironment.java:375)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.findType(JavaSearchNameEnvironment.java:460)
	at org.eclipse.jdt.internal.compiler.env.IModuleAwareNameEnvironment.findType(IModuleAwareNameEnvironment.java:100)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createPlainPackage(LookupEnvironment.java:1177)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.buildTypeBindings(CompilationUnitScope.java:145)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.buildTypeBindings(LookupEnvironment.java:524)
	at org.eclipse.jdt.internal.core.search.indexing.SourceIndexer.resolveDocument(SourceIndexer.java:183)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.resolveDocument(JavaSearchParticipant.java:125)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexResolvedDocument(IndexManager.java:668)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager$2.execute(IndexManager.java:1272)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:541)
	at org.eclipse.jdt.internal.core.search.processing.JobManager$$Lambda/0x00000070012c4e80.run(Unknown Source)
	at java.lang.Thread.runWith(java.base@21.0.5/Unknown Source)
	at java.lang.Thread.run(java.base@21.0.5/Unknown Source)

```

and several other threads trying to use the index at the same time, many looking like this:

```
"ForkJoinPool.commonPool-worker-1" #316 [86791] daemon prio=5 os_prio=31 cpu=83.38ms elapsed=104.33s tid=0x0000000107c9ec00 nid=86791 in Object.wait()  [0x0000000175411000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait0(java.base@21.0.5/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@21.0.5/Unknown Source)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.performConcurrentJob(JobManager.java:362)
	- locked <0x00000007c0c00e58> (a org.eclipse.jdt.internal.core.search.indexing.IndexManager)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:260)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:620)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:677)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.resolveMainClassUnderPaths(ResolveMainClassHandler.java:149)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.resolveMainClassCore(ResolveMainClassHandler.java:94)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.resolveMainClass(ResolveMainClassHandler.java:65)
	at com.microsoft.java.debug.plugin.internal.JavaDebugDelegateCommandHandler.executeCommand(JavaDebugDelegateCommandHandler.java:65)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:610)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$$Lambda/0x0000007001668418.apply(Unknown Source)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer$$Lambda/0x0000007001668650.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(java.base@21.0.5/Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.exec(java.base@21.0.5/Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@21.0.5/Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@21.0.5/Unknown Source)
	at java.util.concurrent.ForkJoinPool.scan(java.base@21.0.5/Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@21.0.5/Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@21.0.5/Unknown Source)

```

I am not exactly sure why those calls cause the index to get stuck, but this is the piece where we need to investigate this in more detail, I think.

It also looks to me like disabling the `Spring Boot Dashboard` extension works around this issue. At least that made this work for me and I only lost the `Spring Boot Dashboard` functionality, not everything from the Spring Tools. Can you verify that this works for you, too, @CloudSen ?

**Comment by martinlippert** [comment]
For the deeper investigation into the underlying issue, I filed https://github.com/microsoft/vscode-spring-boot-dashboard/issues/352 for the dashboard project.

**Comment by CloudSen** [comment]
Thank you for taking the time to investigate this issue. Yes, after
disabling the Spring Boot Dashboard, I was also able to build successfully.
Previously, I mentioned that I had disabled Spring Boot Tools, not
realizing that it would also disable the Spring Boot Dashboard plugin. So,
this isn't an issue with Spring Boot Tools, right? Things have gotten a bit
tricky.


Harder,Better,Faster,Stronger.


Martin Lippert ***@***.***>于2025年1月27日 周一18:26写道：

**Comment by CloudSen** [comment]
I will continue to follow up on this issue. Thank you very much ~


Harder,Better,Faster,Stronger.


Martin Lippert ***@***.***>于2025年1月27日 周一18:33写道：

**Comment by martinlippert** [comment]
> Thank you for taking the time to investigate this issue. Yes, after
> disabling the Spring Boot Dashboard, I was also able to build successfully.

That is good news!!! 👍

> Previously, I mentioned that I had disabled Spring Boot Tools, not
> realizing that it would also disable the Spring Boot Dashboard plugin. So,
> this isn't an issue with Spring Boot Tools, right? Things have gotten a bit
> tricky.

Yeah, no worries, this is totally not obvious from the outside... 😂
