### ISSUE TITLE
NoSuchMethodError in LSPTextHover after 2020-03 upgrade

### ISSUE THREAD

**Issue by davidmichaelkarr** [spring-projects/sts4#423]
I just upgraded to Eclipse 2020-03 yesterday.  I believe the corresponding Spring IDE version has not been released yet, so perhaps this issue will be resolved with that update.

In 2020-03, while debugging an issue that is likely unrelated to Spring IDE (run configuration doesn't automatically have source for project), I noticed the following in the workspace log (I pasted the entire stack trace, but I only see the "end" of it in preview mode):

```java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.eclipse.lsp4j.services.TextDocumentService.hover(Lorg/eclipse/lsp4j/TextDocumentPositionParams;)Ljava/util/concurrent/CompletableFuture;
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2093)
	at org.springframework.tooling.boot.ls.jdt.LSPTextHover.getHoverInfo(LSPTextHover.java:109)
	at org.springframework.tooling.boot.ls.jdt.SpringBootJavaHoverProvider.getHoverInfo2(SpringBootJavaHoverProvider.java:42)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:165)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:132)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:89)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)
Caused by: java.lang.NoSuchMethodError: org.eclipse.lsp4j.services.TextDocumentService.hover(Lorg/eclipse/lsp4j/TextDocumentPositionParams;)Ljava/util/concurrent/CompletableFuture;
	at org.springframework.tooling.boot.ls.jdt.LSPTextHover.lambda$11(LSPTextHover.java:237)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.springframework.tooling.boot.ls.jdt.LSPTextHover.lambda$10(LSPTextHover.java:246)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

Despite the exception, I'm not sure what symptom this is causing. I imagine it's subtle, if at all.

**Comment by martinlippert** [comment]
Looks like you are running Spring Tools 4, so I moved the issue to the sts4 GH tracker.

The error message above happens indeed due to an incompatibility between the latest Eclipse 2020-03 version and the Spring Tools 4. We just released Spring Tools 4.6.0 and updating to that should fix the above issue.

If the issue remains, we need to dive a bit deeper and take a look at the exact versions that got updated, etc, but we should do that only if the issue still appears after the update.

**Comment by davidmichaelkarr** [comment]
I imagine "just released" is relative, as I still don't see it when I check for updates.  Hopefully tomorrow.

**Comment by davidmichaelkarr** [comment]
The other odd thing I just realized is that when I look in the Marketplace Client, I do see the 4.6.0.RELEASE, and it says "Installed".  When I check "About", it says I have 4.5.1.  I still get nothing when I check for updates.  Something is messed up here.

**Comment by davidmichaelkarr** [comment]
I'm guessing what I'll have to do is uninstall the Spring components, and then reinstall them. Is that the only path here?

**Comment by martinlippert** [comment]
I am not sure why the update to Spring Tools 4.6.0 is not showing up for you. It is probably related to the set of update sites that you have and the set of features that you have already installed. Hard to say without looking at your install.

In case you started with the Spring Tools 4 for Eclipse distribution from https://spring.io/tools, there should be this update site URL installed in your preferences:

https://download.springsource.com/release/TOOLS/sts4/update/latest

This update site points to the latest Spring Tools 4 release as well as the latest compatible Eclipse release. This is the main update site that we use in order to update Spring Tools 4 installations to both the newest Eclipse and the newest Spring Tools 4 version at the same time.

In order to "repair" your installation, you could try to install the latest Spring Tools 4 features manually into your Eclipse installation. In case you have updated everything to Eclipse 2020-03, you could use this update site URL in the "Install New Software" dialog:

https://download.springsource.com/release/TOOLS/sts4/update/e4.15/

Please select all the main Spring Tools 4 features in there. If you have them installed already, an update will happen instead. The list of features is mentioned on our wiki:

https://github.com/spring-projects/sts4/wiki/Installation#install-spring-tools-4-into-an-existing-eclipse-via-a-p2-repo

In case the installation results in an error being reported, we would need to take a look at the error message. This happens if there is an incompatibility detected for the install, which reveals the details of the problem. In that case, please paste the error message here and we can take a look at that.

As a last resort, there is always the option to start with a fresh install from https://spring.io/tools. In case you have additional plugins installed, you can re-install them into a fresh installation either via a script or via an import wizard in your new install.

Hope this helps!!!

**Comment by davidmichaelkarr** [comment]
I started with the Eclipse Java installation, not the STS install, and I installed Spring IDE 4 from the marketplace.  The update site I have in my preferences is "Spring Tool Suite 4 - https://download.springsource.com/release/TOOLS/sts4/update/e4.15/".  When I attempt to "Install New Software" from that update site, with "Hide items that are already installed" checked, it doesn't show the 4.6.0 choices.  It shows a handful of miscellaneous items, including the 4.5.1 version of the "Branding Feature".  If I uncheck the "Hide" checkbox, it shows the 4.5.1 features that I already have installed.

**Comment by martinlippert** [comment]
Looks like the network delivers outdated content here for you. One attempt to solve this might be to go to the preferences and press "Reload" for that update site. Maybe that already helps. If not, feel free to try:

https://dist.springsource.com/release/TOOLS/sts4/update/e4.15/

Maybe that delivers the up-to-date content for you. Hope that helps!

**Comment by davidmichaelkarr** [comment]
Interesting.  That did it.  I've never really noticed that button before.  I'm surprised I had to do that to get this to work.

After I clicked that and dismissed the dialog, I just checked for update, and they came up.

**Comment by martinlippert** [comment]
Good to hear that the updates show up now, hope you can get all the necessary plugins updated and installed now. To be honest, I have no idea why this "reload" was necessary in your case. It definitely should not be necessary. Maybe something went wrong under the hood of the update mechanism or some stale cache data lurked around somewhere in the install. Sorry for the trouble, hope the next update will work smoothly.
