### ISSUE TITLE
[vscode extension] not work when change LightWeight mode to Standard

### ISSUE THREAD

**Issue by caiqichang** [spring-projects/sts4#628]
**Describe the bug**

sts4 edition: vscode extension

If i open a project on `LightWeight` mode at first then change to `Standard`, the extension does not work.

It only works if the project open on `Standard` mode at the beginning.

**To Reproduce**

**Sample**

**Comment by martinlippert** [comment]
I am not exactly sure what you mean with Lightweight vs. Standard mode? Can you elaborate on this or provide a few screenshots or anything that describes the issue in more detail? That would be great.

**Comment by caiqichang** [comment]
@martinlippert 
It is property of extension `Language Support for Java(TM) by Red Hat` ( dependency of `Spring Boot Tools` ).
![QQ截图20210427171434](https://user-images.githubusercontent.com/20108732/116217780-812e2380-a77c-11eb-9d47-40a48d8d8160.jpg)

**Comment by martinlippert** [comment]
Thanks for the screenshot, that helps. What exactly are the steps that you follow to reproduce the problem? Did you select the `Lightweight` mode in the preferences, import the project, and then switch this preference manually to `Standard`? Or do you trigger this in a different way?

**Comment by caiqichang** [comment]
@martinlippert 
- Situtation 1: 
Mode is set to `Standard` default, open a project, and STS work well.

- Situtation 2:
Mode is set to `LightWeight` default, open a project, change mode to `Standard` manually (use the button on bottom-right of vscode, see the screenshot), and STS not work.

![QQ截图20210427173741](https://user-images.githubusercontent.com/20108732/116220687-7c1ea380-a77f-11eb-9fc9-aaee70e4731c.jpg)

**Comment by martinlippert** [comment]
@caiqichang Yepp, I can reproduce, thanks for reporting and the additional details. We will take a look.

**Comment by caiqichang** [comment]
@martinlippert 
I found that other extension like `Spring Boot Dashboard` also has this problem, maybe it should be fixed by upstream.

**Comment by martinlippert** [comment]
@caiqichang The `Spring Boot Dashboard` extension interacts with the Spring Boot Tools in order to gather information about the apps to show, so I assume the issue with the `Spring Boot Dashboard` goes back to the underlying issue with the Spring Tools extension.

**Comment by BoykoAlex** [comment]
Sounded to me like we'd like to fix the default case where **Light-weight** JDT LS starts first and then somehow replaced with the **Standard** when it is fully started. The issue is when the standard LS is fully functional we won't attempt to register classpath listener again or don't wait for standard jdt ls to start when registering classpath listener

**Comment by kdvolder** [comment]
Hmm, okay. Yes, as a user I would expect that to work, and it should be possible somehow to make that work. 

The question is though how would our extension be able to even know that the JDT server's 'mode' was changed and therefore we need to try again to connect our classpath listeners. I suppose we could just 'keep trying' repeatedly no matter what, but that might not be such a great idea for performance reasons.

**Comment by BoykoAlex** [comment]
Red Hat Java 0.79.1 seems to have it fixed by prompting the user to restart vscode for launch mode setting switch. After that restart everything works as expected.
Please double -check this @caiqichang

**Comment by martinlippert** [comment]
I am re-opening this issue. To be it looks like this still doesn't work when you start VS Code with the Java support to be configured to launch in Lightweight mode. I then open a Java file and I can see in the outline view the Java content (which is correct). When I switch via the preferences to a different mode, I am prompted for a restart and everything works just fine. But if I switch to the standard mode via the little rocket icon on the status bar below the editor, I am prompted if I really want to enable the standard mode, and if I click yes, the Java support is switched to the standard mode, but the Spring Boot support isn't notified of anything, so continues to do nothing.

**Comment by BoykoAlex** [comment]
Fixed with 94dd78b2fce7def6fb5508cf4fcd4c5c9f601167

Doesn't look like we can avoid adding/removing classpath listener to jdt ls at runtime.

JDT launches two kinds of LS now: syntax and standard. We can either add classpath listener to both because syntax server is shutdown if standard started or just add a listener to the standard ls (which is done in the current solution).

If the launch mode is hybrid syntax ls started first then once standard ls is started the launchMode property becomes **Standard** and then boot ls adds a classpath listener.

(@martinlippert  Hope this tiny bit of explanation makes sense, but we can obviously chat more about it ouitside of github)
