### ISSUE TITLE
organize imports causes communication issues with the language server

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#806]
I have the Rest Service example running, added actuators, see live hovers in the editor. While seeing that, I add a new private field, add a value annotation, running content-assist in the value parameter, all that works fine.

Then, I delete the code around the new private field and an unused import warning shows up. Everything seems to be fine up to here. Then I do an "organize imports" and after that, the green hovers seem to be totally off and a never-ending background job appears `Language Server Background Job`.

I can cleanup the situation in the editor again when typing into the editor (after the next keystroke, the green liver hover highlights are perfectly fine again), but the background job is still sitting around.

I think we need to investigate and fix both issues here.

**Comment by BoykoAlex** [comment]
Might be related to the Rewrite integration... parsing and then reconciling. However, not sure if perform any of the Rewrite recipes or parsing in a job except for applying recipes to projects... I'll probably have a look at this

**Comment by BoykoAlex** [comment]
Background job seems like some non-terminated progress... i.e. exception thrown but finally block missing progress done... something around this

**Comment by BoykoAlex** [comment]
This should fix the annoying background job: 1f4822228aaff7da4e0f6f86fc76f3460778f642

**Comment by martinlippert** [comment]
The issue with the annoying `Language Server Background Job` is indeed fixed, but the green live hover highlights are still broken right after the "organize imports" action, therefore re-opening this issue.

**Comment by BoykoAlex** [comment]
Ouch... yes indeed the issue is about the garbled live hovers as well. This part will be probably more difficult to address :-\

**Comment by martinlippert** [comment]
I think this is fixed now. Closing.
